문자열 메소드

In [ ]:
a = 'python is easy!'
a

'python is easy!'

In [ ]:
a.split(maxsplit=1)

['python', 'is easy!']

In [ ]:
a.capitalize()

'Python is easy!'

In [ ]:
a.upper()

'PYTHON IS EASY!'

In [ ]:
a.lower()

'python is easy!'

In [ ]:
a.find('y')

1

In [ ]:
a.rfind('y')

13

In [ ]:
sl = a.split()
sl

['python', 'is', 'easy!']

In [ ]:
' '.join(sl)

'python is easy!'

In [ ]:
'#'.join(sl)

'python#is#easy!'

list comprehension

In [ ]:
sl

['python', 'is', 'easy!']

In [ ]:
ul = []
for s in sl:
    ul.append(s.upper())

ul

['PYTHON', 'IS', 'EASY!']

In [ ]:
[s.upper() for s in sl]

['PYTHON', 'IS', 'EASY!']

list comprehension으로 구구단을 만들자.

In [ ]:
[[num*j for j in range(1, 10)] for num in range(2, 10)]

[[2, 4, 6, 8, 10, 12, 14, 16, 18],
 [3, 6, 9, 12, 15, 18, 21, 24, 27],
 [4, 8, 12, 16, 20, 24, 28, 32, 36],
 [5, 10, 15, 20, 25, 30, 35, 40, 45],
 [6, 12, 18, 24, 30, 36, 42, 48, 54],
 [7, 14, 21, 28, 35, 42, 49, 56, 63],
 [8, 16, 24, 32, 40, 48, 56, 64, 72],
 [9, 18, 27, 36, 45, 54, 63, 72, 81]]

튜닝 파라미터의 모든 조합을 리턴하는 함수를 생성해보자.

In [ ]:
params = {'n_layer':[1, 2, 3],
          'units': [8, 16, 32],
          'optim': ['a', 'b', 'c']}

In [ ]:
keys = params.keys()
keys

dict_keys(['n_layer', 'units', 'optim'])

In [ ]:
params['n_layer']

[1, 2, 3]

In [ ]:
retall = []
keys = params.keys()
for i, k in enumerate(keys):
    if i == 0:
        for v in params[k]:
            d = {}
            d[k] = v
            retall.append(d)
    else:
        tmp = retall.copy()
        retall = []
        for d in tmp:
            for v in params[k]:
                d = d.copy()
                d[k] = v
                retall.append(d)

retall

[{'n_layer': 1, 'units': 8, 'optim': 'a'},
 {'n_layer': 1, 'units': 8, 'optim': 'b'},
 {'n_layer': 1, 'units': 8, 'optim': 'c'},
 {'n_layer': 1, 'units': 16, 'optim': 'a'},
 {'n_layer': 1, 'units': 16, 'optim': 'b'},
 {'n_layer': 1, 'units': 16, 'optim': 'c'},
 {'n_layer': 1, 'units': 32, 'optim': 'a'},
 {'n_layer': 1, 'units': 32, 'optim': 'b'},
 {'n_layer': 1, 'units': 32, 'optim': 'c'},
 {'n_layer': 2, 'units': 8, 'optim': 'a'},
 {'n_layer': 2, 'units': 8, 'optim': 'b'},
 {'n_layer': 2, 'units': 8, 'optim': 'c'},
 {'n_layer': 2, 'units': 16, 'optim': 'a'},
 {'n_layer': 2, 'units': 16, 'optim': 'b'},
 {'n_layer': 2, 'units': 16, 'optim': 'c'},
 {'n_layer': 2, 'units': 32, 'optim': 'a'},
 {'n_layer': 2, 'units': 32, 'optim': 'b'},
 {'n_layer': 2, 'units': 32, 'optim': 'c'},
 {'n_layer': 3, 'units': 8, 'optim': 'a'},
 {'n_layer': 3, 'units': 8, 'optim': 'b'},
 {'n_layer': 3, 'units': 8, 'optim': 'c'},
 {'n_layer': 3, 'units': 16, 'optim': 'a'},
 {'n_layer': 3, 'units': 16, 'optim': 'b'

In [ ]:
def retallparams(params):
    retall = []
    keys = params.keys()
    for i, k in enumerate(keys):
        if i == 0:
            for v in params[k]:
                d = {}
                d[k] = v
                retall.append(d)
        else:
            tmp = retall.copy()
            retall = []
            for d in tmp:
                for v in params[k]:
                    d = d.copy()
                    d[k] = v
                    retall.append(d)

    return retall

In [ ]:
retallparams(params)

[{'n_layer': 1, 'units': 8, 'optim': 'a'},
 {'n_layer': 1, 'units': 8, 'optim': 'b'},
 {'n_layer': 1, 'units': 8, 'optim': 'c'},
 {'n_layer': 1, 'units': 16, 'optim': 'a'},
 {'n_layer': 1, 'units': 16, 'optim': 'b'},
 {'n_layer': 1, 'units': 16, 'optim': 'c'},
 {'n_layer': 1, 'units': 32, 'optim': 'a'},
 {'n_layer': 1, 'units': 32, 'optim': 'b'},
 {'n_layer': 1, 'units': 32, 'optim': 'c'},
 {'n_layer': 2, 'units': 8, 'optim': 'a'},
 {'n_layer': 2, 'units': 8, 'optim': 'b'},
 {'n_layer': 2, 'units': 8, 'optim': 'c'},
 {'n_layer': 2, 'units': 16, 'optim': 'a'},
 {'n_layer': 2, 'units': 16, 'optim': 'b'},
 {'n_layer': 2, 'units': 16, 'optim': 'c'},
 {'n_layer': 2, 'units': 32, 'optim': 'a'},
 {'n_layer': 2, 'units': 32, 'optim': 'b'},
 {'n_layer': 2, 'units': 32, 'optim': 'c'},
 {'n_layer': 3, 'units': 8, 'optim': 'a'},
 {'n_layer': 3, 'units': 8, 'optim': 'b'},
 {'n_layer': 3, 'units': 8, 'optim': 'c'},
 {'n_layer': 3, 'units': 16, 'optim': 'a'},
 {'n_layer': 3, 'units': 16, 'optim': 'b'

In [ ]:
def add(a, b):
    return a + b

In [ ]:
args = (1, 2)
add(*args)

3

In [ ]:
add(*(1,2))

3

In [ ]:
# add(args) # add((1, 2))
# add(*args) # add(*(1,2)) => add(1,2)
add(1,2)

3

In [ ]:
kwargs = {'a':1, 'b':2}

In [ ]:
kwargs['a']

1

In [ ]:
add(**kwargs)

3

In [ ]:
add(a=1, b=2)

3

In [1]:
import numpy as np

In [2]:
h = np.array([-.5, 2.1, 0.3, -1.2])
h

array([-0.5,  2.1,  0.3, -1.2])

In [3]:
def relu(x):
    return np.maximum(x, 0)

In [4]:
relu(h)

array([0. , 2.1, 0.3, 0. ])

In [7]:
def softmax(s):
    return np.exp(s) / np.exp(s).sum()

In [8]:
prob = softmax(h)
prob

array([0.05818736, 0.78341932, 0.12949834, 0.02889499])

In [9]:
prob.sum()

0.9999999999999999

In [10]:
prob.argmax()

1